version: '3'
services:
  nodejsservice:
    build: ./nodejsservice
    command: nodemon --exec npm run start
    volumes:
      - "./nodejsservice/app:/home/node"
    ports:
      - "3000:3000"
    restart: always    